---
- name: "Update apt cache"
  become: true
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  tags: repo

- name: "Install required packages"
  become: true
  ansible.builtin.apt:
    name: "{{ packages_present_apt }}"
    state: latest
  ignore_errors: true
  tags: repo

- name: "Create required directories"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/apt/keyrings

- name: "Manage Debian repositories"
  ansible.builtin.include_tasks: "repo/{{ item }}.yml"
  loop: "{{ repos + (repos_absent | d([])) }}"
  vars:
    rname: "{{ item }}"
  tags: repo

- name: "Manage APT preferences"
  ansible.builtin.include_tasks: "preferences.yml"
  tags: preferences

- name: "Manage packages"
  vars:
    task_files: |
      {% set include_task_files = [] %}
      {% if packages_present is defined %}
      {%    set include_task_files = include_task_files + ['install.yml'] %}
      {% endif %}
      {% if packages_absent is defined %}
      {%    set include_task_files = include_task_files + ['uninstall.yml'] %}
      {% endif %}
      {% if packages_hold is defined %}
      {%    set include_task_files = include_task_files + ['hold.yml'] %}
      {% endif %}
      {% if packages_unhold is defined %}
      {%    set include_task_files = include_task_files + ['unhold.yml'] %}
      {% endif %}
      {{ include_task_files }}
  ansible.builtin.include_tasks: "package/{{ item }}"
  loop: "{{ task_files }}"
  tags:
    - packages
    - package
    - pkg
